"""add_multi_tenant_and_mineru_support

Revision ID: 023e2c73bbf7
Revises: 0001_init
Create Date: 2026-01-05 00:49:38.812608

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '023e2c73bbf7'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable columns first
    op.add_column('documents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('markdown_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('markdown_status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('markdown_error', sa.Text(), nullable=True))

    # Set owner_id = uploader_id for existing documents
    op.execute("UPDATE documents SET owner_id = uploader_id WHERE owner_id IS NULL AND uploader_id IS NOT NULL")

    # Set owner_id to admin user (id=1) for documents without uploader
    op.execute("UPDATE documents SET owner_id = 1 WHERE owner_id IS NULL")

    # Now make owner_id NOT NULL
    op.alter_column('documents', 'owner_id', nullable=False)

    # Create index and foreign key
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index('ix_documents_status_owner', 'documents', ['status', 'owner_id'], unique=False)
    op.create_index('ix_documents_markdown_status', 'documents', ['markdown_status'], unique=False)
    op.create_foreign_key('fk_documents_owner_id', 'documents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_owner_id', 'documents', type_='foreignkey')
    op.drop_index('ix_documents_markdown_status', table_name='documents')
    op.drop_index('ix_documents_status_owner', table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_column('documents', 'markdown_error')
    op.drop_column('documents', 'markdown_status')
    op.drop_column('documents', 'markdown_path')
    op.drop_column('documents', 'owner_id')
    # ### end Alembic commands ###

