"""add ocr_mode and deskew to documents

Revision ID: fc28db05208f
Revises: f0b71ba88af0
Create Date: 2026-01-10 01:05:22.487008

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'fc28db05208f'
down_revision = 'f0b71ba88af0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_mode', sa.String(length=16), nullable=True))
    op.add_column('documents', sa.Column('deskew', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deskew')
    op.drop_column('documents', 'ocr_mode')
    # ### end Alembic commands ###

